module.exports = { 
    AuthRoutes: require('./auth'),
    ActivityRoutes: require('./activity'),
    DepartmentRoutes: require('./department'),
    DeviceRoutes: require('./device'),
    DeviceTypesRoutes: require('./device_type'),
    MonitorRoutes: require('./monitor'),
    ManufacturerRoutes: require('./manufacturer'),
    PingRoutes: require('./ping'),
    PhotoRoutes: require('./photo'),
    RevisionRoutes: require('./revision'),
    StaffRoutes: require('./staff'),
    TicketRoutes: require('./ticket'),
    TicketTypesRoutes: require('./ticket_type'),
    TransferRoutes: require('./transfer'),
};